#!/usr/bin/env bash
#
# capacity.sh — B3 offline capacity harness for rabbot (docs/PERFORMANCE.md).
#
# WHAT IT DOES
#   Builds rabbot, starts the LOOPBACK-ONLY synthetic origin (scripts/bench/
#   corpussite), writes a SCRATCH config + DB that points the daemon at that
#   origin with N pages and a DELIBERATELY ACCELERATED crawl cadence, runs the
#   daemon under a 1 vCPU / 1 GiB resource cap, and samples resident memory
#   (VmRSS from /proc/<pid>/status) and the SQLite DB file size every 10 s for a
#   configured duration. It writes capacity-<N>.csv (header
#   "elapsed_s,vmrss_kb,db_bytes") for each N in the sweep {500, 2000, 10000}.
#
#   Everything runs on-box against 127.0.0.1 ONLY. No third-party host is ever
#   contacted: the corpus origin is loopback, and the daemon's alert webhook is a
#   loopback discard endpoint served by corpussite. The script NEVER echoes a
#   secret (the control token is generated by the daemon into the scratch config
#   dir and is never printed).
#
# ACCELERATED CADENCE IS A STRESS UPPER BOUND — NOT THE STEADY STATE
#   The scratch config sets a very short per-host rate and recheck interval so the
#   daemon hammers the corpus as fast as it can. This is a deliberate WORST-CASE
#   load to find the resource ceiling; it is NOT how rabbot crawls real sites
#   (the shipped defaults are polite: a multi-second per-host rate and a
#   minutes-to-hours recheck cadence). docs/PERFORMANCE.md discloses this, and
#   the script prints the same disclaimer below.
#
# RESOURCE CAP
#   Linux default: systemd-run --scope -p MemoryMax=1G -p CPUQuota=100% (one
#   core). A user-session systemd is sufficient (systemd-run --user --scope).
#
#   Docker ALTERNATIVE (same 1 vCPU / 1 GiB envelope), if systemd-run is
#   unavailable — run rabbot inside a minimal Go image with the repo mounted:
#     docker run --rm --cpus=1 --memory=1g \
#       -v "$PWD:/src" -w /src \
#       -e XDG_CONFIG_HOME=/src/.benchscratch/cfg \
#       golang:1.26.4 ./rabbot run
#   (corpussite and the daemon both run on the container's loopback; build the
#   rabbot binary first so the container only runs it.)
#
# SSRF PRECONDITION (HANDLED AUTOMATICALLY)
#   rabbot's crawl fetcher refuses to dial loopback/private addresses (the SSRF
#   guard, internal/fetcher/ssrf.go) and the SHIPPED `rabbot run` binary exposes
#   NO flag/env to relax it — by design. So the stock release binary CANNOT crawl
#   this loopback corpus: every fetch would classify as unreachable and the
#   capacity numbers would be meaningless.
#
#   This script therefore builds and runs a small BENCH-ONLY daemon
#   (scripts/bench/benchdaemon, compiled with `-tags benchdaemon`) that is the
#   REAL daemon with the crawl fetcher's AllowPrivate flipped — the same switch
#   the in-process end-to-end tests use. The build tag keeps it PHYSICALLY OUT of
#   the shipped binary (goreleaser builds only ./cmd/rabbot, untagged), so the
#   release never relaxes its SSRF guard, and no flag or config key is added to
#   the shipped binary. To run a pre-built daemon instead, set
#       RABBOT_BENCH_BIN=/path/to/your-daemon ./scripts/bench/capacity.sh
#   and the script uses that binary as-is.
#
# USAGE
#   scripts/bench/capacity.sh                 # sweep N in {500,2000,10000}
#   N_SWEEP="500 2000" scripts/bench/capacity.sh
#   DURATION_S=120 SAMPLE_EVERY_S=10 scripts/bench/capacity.sh
#   CHURN_PCT=5 CHURN_EVERY=30s scripts/bench/capacity.sh
#
# This is dev tooling: goreleaser builds only ./cmd/rabbot, so nothing here ships.

set -euo pipefail

# --- configuration (env-overridable; all values are integers/durations) --------
N_SWEEP="${N_SWEEP:-500 2000 10000}"   # page counts to sweep
DURATION_S="${DURATION_S:-180}"        # seconds to sample per N
SAMPLE_EVERY_S="${SAMPLE_EVERY_S:-10}" # sampling period in seconds
CHURN_PCT="${CHURN_PCT:-5}"            # % of pages mutated each churn interval
CHURN_EVERY="${CHURN_EVERY:-30s}"      # churn interval
MEM_MAX="${MEM_MAX:-1G}"               # systemd MemoryMax (1 GiB cap)
CPU_QUOTA="${CPU_QUOTA:-100%}"         # systemd CPUQuota (100% = one core)

# Resolve the repo root from this script's location (works regardless of CWD).
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." >/dev/null 2>&1 && pwd)"

# Scratch workspace (gitignored via *.db, capacity-*.csv; the whole dir is local).
SCRATCH_DIR="${REPO_ROOT}/.benchscratch"

# --- child-process bookkeeping + cleanup trap ----------------------------------
# We record every child PID we start and kill the whole set on exit, so a
# Ctrl-C or an error never leaves a daemon or corpussite running.
CHILD_PIDS=()

cleanup() {
  local pid
  for pid in "${CHILD_PIDS[@]:-}"; do
    if [[ -n "${pid}" ]] && kill -0 "${pid}" 2>/dev/null; then
      kill "${pid}" 2>/dev/null || true
    fi
  done
  # Give them a moment, then hard-kill any survivor.
  sleep 1 || true
  for pid in "${CHILD_PIDS[@]:-}"; do
    if [[ -n "${pid}" ]] && kill -0 "${pid}" 2>/dev/null; then
      kill -9 "${pid}" 2>/dev/null || true
    fi
  done
}
trap cleanup EXIT INT TERM

# --- provenance: print the box identity into the run log -----------------------
print_box_identity() {
  echo "=============================================================="
  echo " rabbot capacity harness — box identity (provenance)"
  echo "=============================================================="
  echo "date(UTC) : $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo "uname -a  : $(uname -a)"
  if command -v nproc >/dev/null 2>&1; then
    echo "nproc     : $(nproc)"
  fi
  if [[ -r /proc/meminfo ]]; then
    echo "MemTotal  : $(awk '/^MemTotal:/ {print $2" "$3}' /proc/meminfo)"
  fi
  if command -v go >/dev/null 2>&1; then
    echo "go version: $(go version)"
  fi
  echo "rabbot rev: $(git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null || echo unknown)"
  echo "--------------------------------------------------------------"
  echo "DISCLAIMER: the crawl cadence below is a DELIBERATE STRESS UPPER"
  echo "BOUND (very short per-host rate + recheck interval). It is NOT the"
  echo "polite default cadence rabbot uses on real sites; these numbers are"
  echo "a worst-case resource ceiling, not steady-state behavior."
  echo "=============================================================="
}

# --- build the daemon binary ---------------------------------------------------
# Always build the shipped binary (proves the tree compiles). If RABBOT_BENCH_BIN
# is provided, RUN that one instead (the loopback-capable build); otherwise warn.
build_and_resolve_binary() {
  echo ">> make build (CGO_ENABLED=0 static binary — proves the shipped tree compiles)" >&2
  make -C "${REPO_ROOT}" build >&2

  if [[ -n "${RABBOT_BENCH_BIN:-}" ]]; then
    if [[ ! -x "${RABBOT_BENCH_BIN}" ]]; then
      echo "ERROR: RABBOT_BENCH_BIN=${RABBOT_BENCH_BIN} is not an executable file" >&2
      exit 1
    fi
    echo ">> using RABBOT_BENCH_BIN for the daemon run: ${RABBOT_BENCH_BIN}" >&2
    RABBOT_BIN="${RABBOT_BENCH_BIN}"
    return
  fi

  # Default: build the loopback-capable bench daemon. It is the REAL daemon with
  # the crawl SSRF guard relaxed (AllowPrivate), compiled ONLY under the
  # `benchdaemon` build tag, so it is excluded from the shipped binary entirely
  # (see the SSRF PRECONDITION header). This is what lets the daemon dial the
  # loopback corpus; the stock ./rabbot, by design, cannot.
  echo ">> building loopback-capable bench daemon (-tags benchdaemon; never shipped)" >&2
  CGO_ENABLED=0 go build -tags benchdaemon \
    -o "${SCRATCH_DIR}/rabbot-benchdaemon" \
    "${REPO_ROOT}/scripts/bench/benchdaemon" >&2
  RABBOT_BIN="${SCRATCH_DIR}/rabbot-benchdaemon"
}

# --- build the corpussite + rsschart dev binaries ------------------------------
build_tools() {
  echo ">> building corpussite + rsschart (dev tools, never shipped)" >&2
  CGO_ENABLED=0 go build -o "${SCRATCH_DIR}/corpussite" "${REPO_ROOT}/scripts/bench/corpussite" >&2
  CGO_ENABLED=0 go build -o "${SCRATCH_DIR}/rsschart" "${REPO_ROOT}/scripts/bench/rsschart" >&2
}

# --- write a scratch config.yaml for one sweep value ---------------------------
# Args: $1 = config-dir (XDG_CONFIG_HOME/rabbot), $2 = data dir, $3 = origin base
# URL (http://127.0.0.1:PORT), $4 = N pages (the per-site page budget). The config
# uses ONLY documented existing keys (no new keys are introduced). The unverified
# throttle is set to the SAME accelerated values as the base tier: an unverified
# site is otherwise floored to a polite 60s spacing, which would defeat the stress
# run — a deliberate positive override loosens the floor (config.go documents that
# the throttle is tunable and a positive value is honored).
write_scratch_config() {
  local cfg_dir="$1" data_dir="$2" origin="$3" pages="$4"
  mkdir -p "${cfg_dir}"
  # The entry URL is a heavy listing page: it links to thousands of in-corpus
  # pages, so the daemon discovers the corpus by following links (no per-URL
  # config needed). follow_links on + a max_pages_per_site of N bounds discovery
  # to the requested page count.
  cat >"${cfg_dir}/config.yaml" <<YAML
# SCRATCH config written by scripts/bench/capacity.sh — DO NOT COMMIT.
# Accelerated cadence = deliberate stress upper bound (see the script header).
data_dir: "${data_dir}"
control:
  port: 0          # ephemeral; the control server is not exercised by the harness
log:
  level: "warn"    # keep the daemon quiet so logging is not the bottleneck
crawler:
  user_agent: "rabbot-bench"
  contact_email: "bench@example.com"   # RFC 2606 reserved; mandatory field
  egress_check_enabled: false          # no outbound IP probe in a loopback run
defaults:
  min_interval: "1s"          # accelerated: URLs become due almost immediately
  max_interval: "5s"
  per_host_concurrency: 8
  per_host_rate: "50ms"       # accelerated: relax politeness for the stress run
  unverified_throttle:
    per_host_rate: "50ms"     # loosen the unverified floor to the base tier
    per_host_concurrency: 8
    max_pages: ${pages}
    min_interval: "1s"
  discovery:
    follow_links: true
    sitemap: false
    max_depth: 8
    max_pages_per_site: ${pages}
notifiers:
  - name: "bench-sink"
    type: "slack-webhook"
    url: "${origin}/webhook"   # loopback discard endpoint (zero egress)
routes:
  - match: {}                  # route every alert to the discard sink
    notifier: "bench-sink"
sites:
  - url: "${origin}/listing/0"
    name: "bench-corpus"
YAML
}

# --- sample VmRSS + DB size every SAMPLE_EVERY_S for DURATION_S ----------------
# Args: $1 = daemon PID, $2 = DB file path, $3 = output CSV path.
sample_loop() {
  local pid="$1" db_path="$2" csv="$3"
  echo "elapsed_s,vmrss_kb,db_bytes" >"${csv}"
  local start now elapsed rss db
  start="$(date +%s)"
  while true; do
    if ! kill -0 "${pid}" 2>/dev/null; then
      echo ">> daemon (pid ${pid}) exited; stopping sampling" >&2
      break
    fi
    now="$(date +%s)"
    elapsed="$(( now - start ))"
    if (( elapsed >= DURATION_S )); then
      break
    fi
    # VmRSS in kB from /proc/<pid>/status (field 2). Empty if the process is gone.
    rss="$(awk '/^VmRSS:/ {print $2}' "/proc/${pid}/status" 2>/dev/null || true)"
    rss="${rss:-0}"
    # DB file size in bytes (0 until the daemon creates it).
    if [[ -f "${db_path}" ]]; then
      db="$(stat -c '%s' "${db_path}" 2>/dev/null || stat -f '%z' "${db_path}" 2>/dev/null || echo 0)"
    else
      db="0"
    fi
    echo "${elapsed},${rss},${db}" >>"${csv}"
    sleep "${SAMPLE_EVERY_S}"
  done
}

# --- run one sweep value end to end -------------------------------------------
run_one() {
  local pages="$1"
  echo
  echo ">> ===== sweep N=${pages} pages ====="

  local work="${SCRATCH_DIR}/n${pages}"
  local cfg_dir="${work}/cfg/rabbot"   # XDG_CONFIG_HOME is ${work}/cfg
  local data_dir="${work}/data"
  local db_path="${data_dir}/rabbot.db"
  local csv="${REPO_ROOT}/capacity-${pages}.csv"
  rm -rf "${work}"
  mkdir -p "${data_dir}"

  # Start the loopback corpus origin on an ephemeral port; capture the real port.
  local corpus_log="${work}/corpussite.log"
  "${SCRATCH_DIR}/corpussite" \
    -addr "127.0.0.1:0" \
    -pages "${pages}" \
    -etag \
    -churn-pct "${CHURN_PCT}" \
    -churn-every "${CHURN_EVERY}" \
    >"${corpus_log}" 2>&1 &
  local corpus_pid=$!
  CHILD_PIDS+=("${corpus_pid}")

  # Wait (up to ~10s) for the "listening 127.0.0.1:PORT ..." line and extract the
  # address. A C-style counter avoids an unused loop variable.
  local origin_addr=""
  local tries=0
  while (( tries < 100 )); do
    if grep -q '^listening ' "${corpus_log}" 2>/dev/null; then
      origin_addr="$(awk '/^listening / {print $2; exit}' "${corpus_log}")"
      break
    fi
    sleep 0.1
    tries=$(( tries + 1 ))
  done
  if [[ -z "${origin_addr}" ]]; then
    echo "ERROR: corpussite did not report a listen address; log follows:" >&2
    cat "${corpus_log}" >&2
    return 1
  fi
  local origin="http://${origin_addr}"
  echo ">> corpus origin: ${origin} (pid ${corpus_pid})"

  write_scratch_config "${cfg_dir}" "${data_dir}" "${origin}" "${pages}"

  # Launch the daemon under the 1 vCPU / 1 GiB cap. Prefer systemd-run --scope;
  # fall back to an uncapped run with a warning if systemd-run is unavailable
  # (the docker alternative is documented in the header for that case).
  local daemon_log="${work}/rabbot.log"
  local pidfile="${work}/daemon.pid"
  local daemon_pid=""
  if command -v systemd-run >/dev/null 2>&1; then
    echo ">> launching daemon under systemd-run --scope (MemoryMax=${MEM_MAX}, CPUQuota=${CPU_QUOTA})"
    # --collect cleans the transient unit when it exits. The daemon inherits the
    # scratch XDG_CONFIG_HOME (loads our config + writes control.token there) and
    # RABBOT_BENCH_PIDFILE (where it records its own PID for sampling — see below).
    RABBOT_BENCH_PIDFILE="${pidfile}" XDG_CONFIG_HOME="${work}/cfg" \
      systemd-run --user --scope --collect \
      -p "MemoryMax=${MEM_MAX}" -p "CPUQuota=${CPU_QUOTA}" \
      "${RABBOT_BIN}" run >"${daemon_log}" 2>&1 &
    daemon_pid=$!
  else
    echo "WARNING: systemd-run not found — running the daemon UNCAPPED." >&2
    echo "WARNING: use the docker --cpus=1 --memory=1g alternative for a real cap." >&2
    RABBOT_BENCH_PIDFILE="${pidfile}" XDG_CONFIG_HOME="${work}/cfg" \
      "${RABBOT_BIN}" run >"${daemon_log}" 2>&1 &
    daemon_pid=$!
  fi
  CHILD_PIDS+=("${daemon_pid}")

  # Resolve the REAL daemon PID for RSS sampling. systemd-run --scope may either
  # exec-replace the launched command (then our $! IS the daemon) or fork+monitor
  # it (then $! is the waiter and the daemon is a child) — which one depends on the
  # systemd version. The bench daemon writes its own getpid() to RABBOT_BENCH_PIDFILE
  # at startup, so prefer that (correct in BOTH cases); fall back to $! if it never
  # appears (e.g. a custom RABBOT_BENCH_BIN that does not write one).
  local waited=0
  while [[ ! -s "${pidfile}" ]] && (( waited < 50 )); do sleep 0.1; waited=$(( waited + 1 )); done
  if [[ -s "${pidfile}" ]]; then
    local real_pid
    real_pid="$(tr -dc '0-9' <"${pidfile}")"
    if [[ -n "${real_pid}" ]] && kill -0 "${real_pid}" 2>/dev/null; then
      daemon_pid="${real_pid}"
      CHILD_PIDS+=("${daemon_pid}")
    fi
  else
    echo "WARNING: ${pidfile} never appeared; sampling \$! (${daemon_pid}) — under a fork+monitor systemd-run this may be the waiter, not rabbot." >&2
  fi
  echo ">> daemon pid ${daemon_pid}; sampling every ${SAMPLE_EVERY_S}s for ${DURATION_S}s -> ${csv}"

  sample_loop "${daemon_pid}" "${db_path}" "${csv}"

  echo ">> N=${pages}: wrote ${csv}"
  if [[ -f "${db_path}" ]]; then
    echo ">> final DB size: $(stat -c '%s' "${db_path}" 2>/dev/null || stat -f '%z' "${db_path}" 2>/dev/null || echo '?') bytes"
  fi

  # Tear down this run's children before the next sweep value (they are also in
  # the global trap, but freeing them now keeps memory clean across the sweep).
  kill "${daemon_pid}" 2>/dev/null || true
  kill "${corpus_pid}" 2>/dev/null || true
  sleep 1 || true
}

main() {
  mkdir -p "${SCRATCH_DIR}"
  print_box_identity
  build_and_resolve_binary
  build_tools

  local n
  for n in ${N_SWEEP}; do
    # Validate each sweep value is a positive integer (no eval, no injection).
    if ! [[ "${n}" =~ ^[0-9]+$ ]] || (( n <= 0 )); then
      echo "ERROR: invalid sweep value '${n}' (must be a positive integer)" >&2
      exit 1
    fi
    run_one "${n}"
  done

  echo
  echo ">> sweep complete. CSVs:"
  for n in ${N_SWEEP}; do
    echo "   capacity-${n}.csv"
  done
  echo ">> render a graph from one CSV, e.g.:"
  echo "     ${SCRATCH_DIR}/rsschart -in capacity-2000.csv -out assets/capacity-rss.svg"
}

main "$@"
