package benchcorpus

import (
	"crypto/sha256"
	"encoding/hex"
	"testing"
)

// goldenIndex is the single page index whose bytes are SHA-pinned per class.
// It is fixed so the golden hashes below are stable; any value works as long as
// the test and the pinned constants agree. 42 is arbitrary.
const goldenIndex = 42

// sizeBand is the documented byte-size envelope for a class. A page that drifts
// outside its band fails TestCorpusIsFixed even if (somehow) its SHA were
// re-pinned — so a silent size regression (a budget edit) is caught
// independently of the hash.
type sizeBand struct {
	class    Class
	min, max int
	// goldenSHA is the SHA-256 (lowercase hex) of Page(class, goldenIndex). It
	// is computed from the generator and pasted here. Editing ANY word-table
	// entry, the page template, or a size budget changes the generated bytes and
	// flips this hash → the test fails. That falsifiability is the point of a
	// "fixed corpus": the hash is the contract, not a comment.
	goldenSHA string
}

// corpusGolden pins the three size classes. Bands match the documented targets
// in the package doc: landing ~8 KiB (6-12 KiB), article ~60 KiB (48-80 KiB),
// listing ~400 KiB (300-500 KiB).
var corpusGolden = []sizeBand{
	{class: Landing, min: 6 << 10, max: 12 << 10, goldenSHA: "d2984c0f01a006fcc3a6fd80e0ded79f72fc60e9144e4deb7f5adda2fdc6b379"},
	{class: Article, min: 48 << 10, max: 80 << 10, goldenSHA: "81a2ad29f82a48ea86e0eb134d88ebe767aa8faac5ae48b30b8e56de10fe5e29"},
	{class: Listing, min: 300 << 10, max: 500 << 10, goldenSHA: "b680109e180cd4d250c3c4bbe9c79ce8ca7cd511fe29469950357826f7bdc51a"},
}

// TestCorpusIsFixed is the golden guard. For each class it asserts:
//
//  1. The SHA-256 of Page(class, goldenIndex) equals the pinned constant —
//     so ANY edit to the generator (one word in a table, one byte in the
//     template) flips the hash and fails. This is what makes "fixed corpus"
//     falsifiable: the corpus cannot silently drift.
//  2. The page size sits inside the documented band — so a budget change that
//     happened to be re-pinned still trips a size-drift failure.
//  3. The generator is deterministic: a second call yields byte-identical
//     output (re-derives the hash from a fresh Page() and compares).
//
// Run: CGO_ENABLED=1 go test -race ./internal/benchcorpus/...
func TestCorpusIsFixed(t *testing.T) {
	for _, g := range corpusGolden {
		t.Run(g.class.String(), func(t *testing.T) {
			page := Page(g.class, goldenIndex)

			// (2) size band.
			if len(page) < g.min || len(page) > g.max {
				t.Errorf("size %d bytes outside documented band [%d,%d] for class %s",
					len(page), g.min, g.max, g.class)
			}

			// (1) golden SHA.
			sum := sha256.Sum256(page)
			got := hex.EncodeToString(sum[:])
			if got != g.goldenSHA {
				t.Errorf("golden SHA mismatch for class %s (size %d):\n  got  %s\n  want %s\n"+
					"if this is an intentional generator change, re-pin the constant; "+
					"if not, the corpus drifted and the benches are no longer comparable",
					g.class, len(page), got, g.goldenSHA)
			}

			// (3) determinism: a second independent call must be byte-identical.
			page2 := Page(g.class, goldenIndex)
			sum2 := sha256.Sum256(page2)
			if hex.EncodeToString(sum2[:]) != got {
				t.Errorf("non-deterministic generation for class %s: two Page() calls differ", g.class)
			}
		})
	}
}

// TestCorpusDeterministicAcrossIndices spot-checks determinism beyond the single
// golden index: a spread of indices must each generate byte-identical output on
// repeated calls. This guards a future edit that introduces nondeterminism
// (e.g. map iteration) that happened not to affect goldenIndex.
func TestCorpusDeterministicAcrossIndices(t *testing.T) {
	for _, c := range []Class{Landing, Article, Listing} {
		for _, i := range []int{0, 1, 7, 100, 999, 12345} {
			a := Page(c, i)
			b := Page(c, i)
			if string(a) != string(b) {
				t.Fatalf("non-deterministic: Page(%s, %d) differs across calls (%d vs %d bytes)",
					c, i, len(a), len(b))
			}
		}
	}
}
