package benchcorpus

// This file holds the FIXED word tables the generator draws from. Content is
// derived from a page's index by integer indexing into these slices (no
// math/rand) — see pick/sentence/paragraph below. The tables are deliberately
// ordinary SEO-prose vocabulary so the readability extractor and SimHash see
// realistic token streams.
//
// FALSIFIABILITY: every word here is part of the generated bytes. Changing,
// adding, or reordering ONE entry in any table below alters at least one page's
// bytes and therefore flips its golden SHA-256 in TestCorpusIsFixed. That is by
// design: the golden test is the guard that the corpus is truly fixed.

// nouns, verbs, adjectives, connectors compose body sentences. Lengths are
// intentionally NOT powers of two so the index-stepping in pick spreads across
// the whole table rather than aliasing to a few entries.
var nouns = []string{
	"platform", "monitor", "gateway", "signal", "crawler", "snapshot", "metric",
	"index", "canonical", "sitemap", "robot", "schema", "payload", "redirect",
	"latency", "throughput", "cadence", "alert", "incident", "baseline",
	"benchmark", "corpus", "scheduler", "frontier", "pipeline", "extractor",
	"diff", "rule", "notifier", "dispatcher", "segment", "graph", "node",
	"document", "heading", "anchor", "image", "header", "response", "request",
}

var verbs = []string{
	"monitors", "rechecks", "extracts", "compares", "schedules", "discovers",
	"persists", "computes", "classifies", "resolves", "validates", "samples",
	"renders", "publishes", "measures", "throttles", "alerts", "records",
	"detects", "recovers", "parses", "fetches", "stores", "ranks", "tracks",
}

var adjectives = []string{
	"static", "single", "honest", "polite", "real-time", "deterministic",
	"reproducible", "lightweight", "self-hosted", "open-source", "pure-Go",
	"resilient", "indexable", "canonical", "structured", "incremental",
	"bounded", "loopback", "portable", "measured", "steady", "cheap",
}

var connectors = []string{
	"and", "so that", "while", "because", "whenever", "before", "after",
	"unless", "until", "since", "as", "though", "without", "across",
}

// headingWords seed short heading phrases (2-4 words). Separate from the prose
// tables so headings read like section titles, not sentences.
var headingWords = []string{
	"Overview", "Architecture", "Crawling", "Extraction", "Diffing", "Rules",
	"Alerting", "Discovery", "Capacity", "Benchmarks", "Deployment", "Methodology",
	"Results", "Limitations", "Reproducing", "Hardware", "Throughput", "Memory",
	"Storage", "Scheduling", "Politeness", "Honesty", "Signals", "Segments",
}

// externalHosts seed the absolute external links a page emits (so extract's
// internal-vs-external classifier does real work). All are RFC 2606 / RFC 6761
// reserved documentation/test domains — none resolve to a real third party.
var externalHosts = []string{
	"https://example.com",
	"https://example.org",
	"https://example.net",
	"https://www.example.com",
	"https://docs.example.org",
}

// schemaTypes seed the JSON-LD @type a page declares, cycling so different pages
// carry different structured-data types (the extract bench reads schema_types).
var schemaTypes = []string{
	"WebPage", "Article", "BlogPosting", "CollectionPage", "TechArticle",
	"Organization", "BreadcrumbList", "FAQPage",
}

// pick returns the table entry at a deterministic offset derived from two
// integers. step is a small odd-ish stride so successive picks walk the whole
// table instead of repeating; the multiply-add mixes the page seed with the word
// position. len(table) is never zero for the tables above. The result depends
// ONLY on its integer inputs — the core of determinism-by-construction.
func pick(table []string, seed, step int) string {
	if seed < 0 {
		seed = -seed
	}
	if step < 0 {
		step = -step
	}
	idx := (seed*31 + step*17) % len(table)
	return table[idx]
}
